# Generated by Django 2.2.5 on 2020-06-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webcashier', '0002_auto_20200604_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='gen_der',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='incustumer',
            name='gender',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
