# Generated by Django 3.0.7 on 2020-06-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webcashier', '0004_auto_20200604_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('face_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=300)),
                ('age', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
            ],
        ),
    ]
