# Generated by Django 3.0.7 on 2020-06-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Webcashier', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(default=20, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='aaa@ubu.ac.th', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='ชาย', max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='09999999999', max_length=20),
        ),
    ]
